image: registry.netresearch.de/magento-ci/ci-toolchain:latest

services:
  - name: registry.netresearch.de/ci-helper/gitlab-worker-dind
    alias: docker

stages:
  - analyze
  - test
  - test-additional
  - build
  - validate
  - deploy

static-analysis:
  stage: analyze
  only:
    - develop
    - master
    - /^(release|hotfix)-.*$/
    - merge_requests
  script:
    - ci-analyze
    - ci-validate-dependencies

runtime-analysis:
  stage: analyze
  extends: .runtime
  only:
    - develop
    - master
    - /^(release|hotfix)-.*$/
    - merge_requests
  variables:
    PHP_VERSION: "7.4"
    MAGENTO_TAG_VERSION: "2.4"
  script:
    - ci-install
    - ci-validate-schema
    - ci-validate-i18n

# Crucial tests (lowest Mage+PHP + highest Mage+PHP)
phpunit-essential-2.3:
  stage: test
  extends: .phpunit
  only:
    - develop
    - master
    - /^(release|hotfix)-.*$/
    - merge_requests
  variables:
    PHP_VERSION: "7.1"
    MAGENTO_TAG_VERSION: "2.3.6"
    MAGENTO_EDITION: "ce"

phpunit-essential-2.4:
  stage: test
  extends: .phpunit
  only:
    - develop
    - master
    - /^(release|hotfix)-.*$/
    - merge_requests
  parallel:
    matrix:
      - PHP_VERSION: "7.4"
        MAGENTO_TAG_VERSION: "2.4"
        MAGENTO_EDITION: ["ee", "ce"]

# Additional tests (in between versions of Magento or PHP)
phpunit-additional-2.3-7.2:
  stage: test-additional
  extends: .phpunit
  parallel:
    matrix:
      - PHP_VERSION: "7.2"
        MAGENTO_TAG_VERSION: "2.3.6"
        MAGENTO_EDITION: ["ee", "ce"]

phpunit-additional-2.3-7.3:
  stage: test-additional
  extends: .phpunit
  parallel:
    matrix:
      - PHP_VERSION: ["7.3"]
        MAGENTO_TAG_VERSION: "2.3"
        MAGENTO_EDITION: ["ee", "ce"]

phpunit-additional-2.4:
  stage: test-additional
  extends: .phpunit
  parallel:
    matrix:
      - PHP_VERSION: "7.3"
        MAGENTO_TAG_VERSION: "2.4"
        MAGENTO_EDITION: ["ee", "ce"]

package-build:
  stage: build
  only:
    - master
    - /^(release|hotfix)-.*$/
  script:
    - zip -r
      -x "*build/*" "*Test/*" "*doc/src*" "*.gitignore" "*.gitlab-ci.yml" "*.git*"
      -o $(ci-get-package-name).zip
      .
  artifacts:
    when: on_success
    paths:
      - ./*.zip

package-validate:
  stage: validate
  only:
    - master
    - /^(release|hotfix)-.*$/
  script:
    - ci-validate $(ci-get-package-name).zip
  dependencies:
    - package-build

github:
  stage: deploy
  when: manual
  only:
    - master
  variables:
    GIT_STRATEGY: "clone"
    VAULT_PATH: "projects/DHL/Github/module-internetmarke"
  before_script:
    - ci-github-before
  script:
    - ci-github

# Templates for jobs running Installation, PHPUnit Integration and MFTF tests
.runtime:
  variables:
    MAGENTO_INSTALL_SAMPLES: "no"
  before_script:
    - ci-install-before
  script:
    - ci-install
  after_script:
    - ci-install-after

# Template for PHPUnit jobs
.phpunit:
  extends: .runtime
  only:
    - develop
    - master
    - /^(release|hotfix)-.*$/
  script:
    - ci-install
    - ci-phpunit-docker Test/Integration/phpunit.xml
