<?php
/**
 * See LICENSE.md for license details.
 */
/** @var \Magento\Backend\Block\Template $block */
/** @var \DeutschePost\Internetmarke\ViewModel\Adminhtml\System\SetupActions $viewModel */
$viewModel = $block->getData('view_model');
?>
<?php if (!$viewModel->isWalletConfigured()): ?>
    <span class="message-warning"><?= $escaper->escapeHtml(__('Please complete your account settings (wallet credentials) to proceed.')) ?></span>
<?php else: ?>
    <a href="<?= $escaper->escapeUrl($viewModel->getFormatsUpdateUrl()); ?>" class="action-default">
        <span><?= $escaper->escapeHtml(__('Update Page Formats')) ?></span>
    </a>
    <a href="<?= $escaper->escapeUrl($viewModel->getProductsUpdateUrl()); ?>" class="action-default">
        <span><?= $escaper->escapeHtml(__('Update Product List')) ?></span>
    </a>
    <p class="note">
        <?php if ($viewModel->getPageFormatCount() > 0): ?>
            <span class="message-success"><?= $escaper->escapeHtml(__('Page formats are available.')) ?></span>
        <?php else: ?>
            <span class="message-warning"><?= $escaper->escapeHtml(__('Please update page formats.')) ?></span>
        <?php endif; ?>
        <?php if ($viewModel->getProductsCount() > 0): ?>
            <span class="message-success"><?= $escaper->escapeHtml(__('Product list is available.')) ?></span>
        <?php else: ?>
            <span class="message-warning"><?= $escaper->escapeHtml(__('Please update shipping products.')) ?></span>
        <?php endif; ?>
    </p>
<?php endif; ?>
