<?php
/**
 * See LICENSE.md for license details.
 */
/** @var \Magento\Framework\View\Element\Template $block */
?>
<div class="col content">
    <p><?= $block->escapeHtml(__('With Deutsche Post Internetmarke, you can ship your orders cost-effectively with mail products.'))?></p>
    <p><?= $block->escapeHtml(__('The module allows to request Deutsche Post Internetmarke stamps directly within your Magento suite.'))?></p>
    <p>
        <?= $block->escapeHtml(__('To get started, you need a Portokasse account.')) ?>
        <?= $block->escapeHtml(
            __(
                'If you do not have a Portokasse account yet, please %1register and create a new account%2.',
                '<a href="' . $block->escapeUrl('https://portokasse.deutschepost.de/portokasse/#!/register/') . '" target="_blank" rel="noreferrer">',
                '</a>'
            ),
            ['a']
        ) ?>
    </p>
</div>
<div class="col side">
    <aside>
        <div class="section">
            <h3><?= $block->escapeHtml(__('Post & DHL and Magento')) ?></h3>
            <p>
                <?= $block->escapeHtml(
                    __(
                        'Having issues configuring the extension? Please take a look at the %1support portal (FAQ)%2 first or contact the support desk:',
                        '<a href="' . $block->escapeUrl('https://dhl.support.netresearch.de/') . '" target="_blank" rel="noreferrer">',
                        '</a>'
                    ),
                    ['a']
                ) ?>
                <a href="mailto:<?= $block->escapeHtml(__('dhl.support@netresearch.de'))?>">
                    <?= $block->escapeHtml(__('dhl.support@netresearch.de'))?>
                </a>
            </p>
        </div>
    </aside>
</div>
