<?php
/**
 * See LICENSE.md for license details.
 */
/** @var \Magento\Framework\View\Element\Template $block */
/** @var \DeutschePost\Internetmarke\ViewModel\Adminhtml\System\Config\InfoBox\Additional $viewModel */
$viewModel = $block->getData('view_model');
?>

<div class="section">
    <h3><?= $escaper->escapeHtml('Deutsche Post Internetmarke') ?></h3>
    <p>
        <?= $escaper->escapeHtml(
            __(
                '%1Internetmarke of Deutsche Post%2 ideally complements DHL Parcel Germany to send small goods in a cost-effective way via mail products.',
                '<a href="' . $escaper->escapeUrl($viewModel->getConfigGroupLink()) . '">',
                '</a>'
            ),
            ['a']
        )
        ?>
    </p>
</div>
